[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    '''inventories\/inventory.template'''
  ]
        
  # Ignore based on any subset of the line
  regexes = []