---

- name: Make sure keycloak application is deployed
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: "{{ ocp4_workload_cloud_architecture_workshop_rhbk_application_name }}"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_rhbk_application_namespace }}"
  register: r_rhbk_application
  until:
    - r_rhbk_application.resources[0].status.sync.status is defined
    - r_rhbk_application.resources[0].status.sync.status == "Synced"
    - r_rhbk_application.resources[0].status.health.status is defined
    - r_rhbk_application.resources[0].status.health.status == "Healthy"
  retries: 40
  delay: 30

- name: "Create namespaces"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_namespaces:
      - name: "{{ ocp4_workload_cloud_architecture_workshop_module_apim_namespace_prefix }}-user"
        managedByArgo: ""
  retries: 10
  delay: 30

- name: "Give users access to projects"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'rolebinding.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_bindings:
      - namespace: "{{ ocp4_workload_cloud_architecture_workshop_module_apim_namespace_prefix }}-user"
        role: "admin"
  retries: 10
  delay: 30

- name: Deploy ArgoCD application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'globex-apim-application.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_module_apim_namespace: "{{ ocp4_workload_cloud_architecture_workshop_module_apim_namespace_prefix }}-user"
