---
- name: "Create user namespaces"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_namespaces:
      - name: "{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-user"
        managedByArgo: ""
      - name: "{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-mw-user"
        managedByArgo: ""
  retries: 10
  delay: 30

- name: "Give users access to projects"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'rolebinding.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_bindings:
      - namespace: "{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-user"
        role: "admin"
      - namespace: "{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-mw-user"
        role: "admin"
  retries: 10
  delay: 30

- name: Deploy Globex application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'globex-application.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_globex_namespace: "{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-user"
    r_cloud_architecture_workshop_globex_mw_namespace: "{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-mw-user"
